name: "🤓 Auto Assign"

on:
  pull_request:
    types:
      - opened
      - ready_for_review
    branches:
      - "feature/**"
      - "bugfix/**"
  push:
    branches-ignore:
      - main

jobs:
  add-reviews:
    name: "🤓 Auto Assign"
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.4
        with:
          configuration-path: ".github/workflows/auto_assign.yml"
          addAssignees: author
